# Assignment 20 : Building & Deploying a Recommendation System

## PART 1 - Data Preprocessing

In [3]:
import pandas as pd

In [4]:
# 1. Load the dataset using pandas
data=pd.read_csv('amazon_product_data_cleaned.csv')

In [5]:
# 2. Print
data.shape

(10002, 15)

In [6]:
data.columns

Index(['Uniq Id', 'Product Name', 'Category', 'Upc Ean Code', 'Selling Price',
       'Model Number', 'About Product', 'Product Specification',
       'Technical Details', 'Shipping Weight', 'Product Dimensions', 'Image',
       'Variants', 'Product Url', 'Is Amazon Seller'],
      dtype='object')

In [7]:
data.head()

,Uniq Id,Product Name,Category,Upc Ean Code,Selling Price,Model Number,About Product,Product Specification,Technical Details,Shipping Weight,Product Dimensions,Image,Variants,Product Url,Is Amazon Seller
0,4c69b61db1fc16e7013b43fc926e502d,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",Sports & Outdoors | Outdoor Recreation | Skate...,NaN,$237.68,NaN,Make sure this fits by entering your model num...,Shipping Weight: 10.7 pounds (View shipping ra...,NaN,10.7 pounds,NaN,https://images-na.ssl-images-amazon.com/images...,https://www.amazon.com/DB-Longboards-CoreFlex-...,https://www.amazon.com/DB-Longboards-CoreFlex-...,Y
1,66d49bbed043f5be260fa9f7fbff5957,"Electronic Snap Circuits Mini Kits Classpack, ...",Toys & Games | Learning & Education | Science ...,NaN,$99.95,55324,Make sure this fits by entering your model num...,Product Dimensions: 14.7 x 11.1 x 10.2...,The snap circuits mini kits classpack provides...,4 pounds,14.7 x 11.1 x 10.2 inches 4.06 pounds,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/Electronic-Circuits-Cla...,Y
2,2c55cae269aebf53838484b0d7dd931a,3Doodler Create Flexy 3D Printing Filament Ref...,Toys & Games | Arts & Crafts | Craft Kits,NaN,$34.99,NaN,Make sure this fits by entering your model num...,ProductDimensions:10.3x3.4x0.8inches|ItemWeigh...,show up to 2 reviews by default No longer are ...,12.8 ounces,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/3Doodler-Plastic-Innova...,Y
3,18018b6bc416dab347b1b7db79994afa,Guillow Airplane Design Studio with Travel Cas...,Toys & Games | Hobbies | Models & Model Kits |...,NaN,$28.91,142,Make 8 different Planes at one time. | Experim...,ProductDimensions:3.5x6.2x13inches|ItemWeight:...,Go to your orders and start the return Select ...,13.4 ounces,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/Guillow-Airplane-Design...,Y
4,e04b990e95bf73bbe6a3fa09785d7cd0,Woodstock- Collage 500 pc Puzzle,Toys & Games | Puzzles | Jigsaw Puzzles,NaN,$17.49,62151,Make sure this fits by entering your model num...,ProductDimensions:1.9x8x10inches|ItemWeight:13...,show up to 2 reviews by default 100% Officiall...,13.4 ounces,NaN,https://images-na.ssl-images-amazon.com/images...,NaN,https://www.amazon.com/Woodstock-Collage-500-p...,Y

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10002 entries, 0 to 10001
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Uniq Id                10002 non-null  object
 1   Product Name           10002 non-null  object
 2   Category               9172 non-null   object
 3   Upc Ean Code           34 non-null     object
 4   Selling Price          9895 non-null   object
 5   Model Number           8230 non-null   object
 6   About Product          9729 non-null   object
 7   Product Specification  8370 non-null   object
 8   Technical Details      9212 non-null   object
 9   Shipping Weight        8864 non-null   object
 10  Product Dimensions     479 non-null    object
 11  Image                  10002 non-null  object
 12  Variants               2478 non-null   object
 13  Product Url            10002 non-null  object
 14  Is Amazon Seller       10002 non-null  object
dtypes: object(15)
memory usage: 1.1+ MB

In [9]:
# 3. Identify text columns used for recommendations

In [10]:
data=data[['Product Name','About Product','Category']]

In [11]:
data['description']=data['About Product']+data['Category']

In [12]:
data.drop(columns=['About Product','Category'],inplace=True)

In [13]:
data.head()

,Product Name,description
0,"DB Longboards CoreFlex Crossbow 41"" Bamboo Fib...",Make sure this fits by entering your model num...
1,"Electronic Snap Circuits Mini Kits Classpack, ...",Make sure this fits by entering your model num...
2,3Doodler Create Flexy 3D Printing Filament Ref...,Make sure this fits by entering your model num...
3,Guillow Airplane Design Studio with Travel Cas...,Make 8 different Planes at one time. | Experim...
4,Woodstock- Collage 500 pc Puzzle,Make sure this fits by entering your model num...

### Text 2: Text Preprocessing for Recommendation

In [14]:
from nltk.corpus import stopwords
import re
import pandas as pd

In [15]:
stopwords=stopwords.words('english')

In [16]:
# Convert into lowercase

data['clean_text']=data['description'].str.lower()
data['Product Name']=data['Product Name'].str.lower()

In [17]:
# remove punctuation and special characters
def punc_removal(text):
    if pd.isna(text):
        return ""
    return re.sub(r"[^\w\s]","",text)

In [18]:
data['clean_text']=data['clean_text'].apply(punc_removal)
data['Product Name']=data['Product Name'].apply(punc_removal)

In [19]:
## remove stopwords

def stopword_remove(text):
    stopword_clean=[]
    for i in text.split():
        if i in stopwords:
            stopword_clean.append("")
        else:
            stopword_clean.append(i)
    return  " ".join(stopword_clean)

In [20]:
data['clean_text']=data['clean_text'].apply(stopword_remove)
data['Product Name']=data['Product Name'].apply(stopword_remove)

In [21]:
# Handle missing values

data['clean_text']=data['clean_text'].fillna('').astype(str)
data['Product Name']=data['Product Name'].fillna('').astype(str)

In [22]:
data.head()

,Product Name,description,clean_text
0,db longboards coreflex crossbow 41 bamboo fibe...,Make sure this fits by entering your model num...,make sure fits entering model number respon...
1,electronic snap circuits mini kits classpack f...,Make sure this fits by entering your model num...,make sure fits entering model number snap c...
2,3doodler create flexy 3d printing filament ref...,Make sure this fits by entering your model num...,make sure fits entering model number smooth...
3,guillow airplane design studio travel case bu...,Make 8 different Planes at one time. | Experim...,make 8 different planes one time experiment ...
4,woodstock collage 500 pc puzzle,Make sure this fits by entering your model num...,make sure fits entering model number puzzle...

## PART 2 - Text Vectorization

### Task 3: Vectorization using TF-Idf

In [23]:
# use tfidfvectorizer() to convert text into vectors

from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
# set parameters
tf=TfidfVectorizer(max_features=5000,ngram_range=(1,2))

In [25]:
matrix_tf=tf.fit_transform(data['clean_text'])

In [26]:
print("Shape of TF-IDF",matrix_tf.shape)

Shape of TF-IDF (10002, 5000)

### Task 4: Similarity Computation

In [27]:
# Compute cosine similarity between all items
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
# Store similarity matrix
similarity_matrix=cosine_similarity(matrix_tf)

In [29]:
print("Shape of similar matrix: ",similarity_matrix.shape)
print(similarity_matrix)

Shape of similar matrix:  (10002, 10002)
[[1.         0.01610139 0.07628795 ... 0.02386013 0.         0.02581929]
 [0.01610139 1.         0.08381165 ... 0.14441477 0.         0.01248704]
 [0.07628795 0.08381165 1.         ... 0.02400401 0.         0.05150844]
 ...
 [0.02386013 0.14441477 0.02400401 ... 1.         0.         0.04828311]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.02581929 0.01248704 0.05150844 ... 0.04828311 0.         1.        ]]

In [30]:
'''
3. Explain brief why cosine similarity is used
- Cosine similarity measures the angle between the vectors
- it is useful in recommendation because it primarily used to give pattern/ direction comparision ratheer than length of documents 
'''

'\n3. Explain brief why cosine similarity is used\n- Cosine similarity measures the angle between the vectors\n- it is useful in recommendation because it primarily used to give pattern/ direction comparision ratheer than length of documents \n'

## PART 4 - Recommendation Logic

### Task 5: Build Recommendation Function

In [53]:
def recommend(product_name, top_n=5):
    product_index=data[data['Product Name']==product_name].index[0]

    similarity_scores=similarity_matrix[product_index]

    product_list=sorted(enumerate(similarity_scores),reverse=True,key=lambda x:x[1])[1:6]

    recommendations=[]

    for index, score in product_list:
        if index!=product_index:
            recommendations.append({'Product Name':data.iloc[index]['Product Name']})

        if len(recommendations) == top_n:
            return recommendations

In [50]:
data['Product Name'][7]

'hoffmaster 120813 doubletipped triangular crayon 88 mm length wrapped 500 packs  2'

In [51]:
import pickle

with open("products.pickle",'wb') as products:
    pickle.dump(data,products)

In [59]:
data

,Product Name,description,clean_text
0,db longboards coreflex crossbow 41 bamboo fibe...,Make sure this fits by entering your model num...,make sure fits entering model number respon...
1,electronic snap circuits mini kits classpack f...,Make sure this fits by entering your model num...,make sure fits entering model number snap c...
2,3doodler create flexy 3d printing filament ref...,Make sure this fits by entering your model num...,make sure fits entering model number smooth...
3,guillow airplane design studio travel case bu...,Make 8 different Planes at one time. | Experim...,make 8 different planes one time experiment ...
4,woodstock collage 500 pc puzzle,Make sure this fits by entering your model num...,make sure fits entering model number puzzle...
...,...,...,...
9997,remedia publications rem536b money activity bo...,NaN,
9998,trends international nfl la chargers hg mobile...,Make sure this fits by entering your model num...,make sure fits entering model number dimens...
9999,newpath learning 10 piece science owls owl pe...,Make sure this fits by entering your model num...,make sure fits entering model number writeo...
10000,disney princess braid set,NaN,
10001,hasegawa ladders lucano step ladder orange,Make sure this fits by entering your model num...,make sure fits entering model number 90 alu...

In [41]:
import joblib

joblib.dump(similarity_matrix,"similarity.joblib",compress=3)

['similarity.joblib']

In [55]:
with open("similarity.pickle",'wb') as similarity:
    pickle.dump(data,similarity)

In [54]:
recommend('guillow airplane design studio  travel case building kit')

[{'Product Name': 'tamiya america inc 172 mosquito fb mkvinf tam60747'},
 {'Product Name': 'tamiya america inc 1 48 grumman f14a tomcat tam61114'},
 {'Product Name': 'tamiya models mosquito fb mkvinf mkii model kit'},
 {'Product Name': 'avionix f14 bombcat updateconversion set'},
 {'Product Name': 'daron worldwide trading daron skymarks etihad a380 1200 w gear vehicle'}]

In [34]:
recommend('3doodler create flexy 3d printing filament refill bundle x5 pack  1000  extruded plastics innovate')

[{'Product Name': 'tech 4 kids 3d magic imagi pen'},
 {'Product Name': '3doodler create 4 pack plastic bundle  licensed farnsworth house stencil 3d pen  included'},
 {'Product Name': 'royal  langnickel colour  number pencil jungle animals'},
 {'Product Name': 'dohvinci 6pack drawing compound mixed colors'},
 {'Product Name': 'chalkscapes mandala stencils  outdoor sidewalk  driveway chalk kit includes 30 chalks 2 stencils  chalk holders 225 inches diam stars  geometry'}]

In [46]:
recommend('hoffmaster 120813 doubletipped triangular crayon 88 mm length wrapped 500 packs  2')

[{'Product Name': 'electronic snap circuits mini kits classpack fm radio motion detector music box set  5'},
 {'Product Name': '3doodler create flexy 3d printing filament refill bundle x5 pack  1000  extruded plastics innovate'},
 {'Product Name': 'guillow airplane design studio  travel case building kit'},
 {'Product Name': 'woodstock collage 500 pc puzzle'},
 {'Product Name': 'terra  battat 4 dinosaur toys medium dinosaurs  kids collectors scientifically accurate designed   paleoartist age 3 4 pc'}]

## PART 4 - Simple App interface

### Task 6: Build UI using Streamlit

In [47]:
# Create a simple interface
# dropdown to select item
# button to generate recommendations

# display recommendation items clearly

## PART 5 - Version Control with Git & Github

### Task 7 : Git and Github setup

In [48]:
'''
1. Initilaize a git repository
2. create a github repository
3. push your project code to github
Repository must include:
- app.py
- requirements.txt
- README.md

'''

'\n1. Initilaize a git repository\n2. create a github repository\n3. push your project code to github\nRepository must include:\n- app.py\n- requirements.txt\n- README.md\n\n'

## PART 6 - Deployment on Render

### Task 8 : Deploy Application on Render

In [ ]:
'''
1. Create a Render account
2. Connect to Render with Github
3. Select your repository
4. Configure:
- Build command
- Start command
5. Deploy the application
'''