# Assignment 18: Text Vectorization Techniques

## PART 1 - One - Hot Encoding (Text Level)

### Task 1: Manual one-hot encoding

In [2]:
import pandas as pd

In [3]:
data=pd.read_csv('final_cleaned_data.csv')

In [4]:
# 1. Select 5 sentences 

sentences=data['final_clean_text'].dropna().iloc[:5].tolist()

for i, sentence in enumerate(sentences, 1):
    print(f"Sentence {i}: {sentence}")

Sentence 1: paperwhite voyage regretsi initially trouble deciding paperwhite voyage review less said thing paperwhite great spending money go voyagefortunately friend owned ended buying paperwhite basis model ppi dollar jump turn pricey voyage page press isnt always sensitive fine specific setting dont need auto light adjustmentits week loving paperwhite regret touch screen receptive easy use keep light specific setting regardless time day case hard change setting either youll changing light level certain time day every readingalso glad went international shipping option amazon extra expense delivery time tracking didnt need worry custom may used third party shipping service
Sentence 2: one simply could ask moreallow preface little history casual reader owned nook simple touch ive read harry potter series girl dragon tattoo series brave new world key title fair say nook get much use many others may gotten theirsfast forward today full week new kindle paperwhite admit im love kindle reading let relate review love reading back kindle investment experience receive buy kindle simply paying screen entire experience included buying amazoni reading hunger game trilogy shall moving onto divergent series soon thing nook hindered past year never inspired pick get hand dive never feeling oh man reading thing awesome however paperwhite feeling desire back simply adore kindle considering purchasing one stop thinking simply go full week downloaded book ton reading still half battery left wellmake happy inspire reader inside
Sentence 3: great want ereaderi enjoying far great reading original fire since fire used make eye hurt read long havent experienced paperwhite yet
Sentence 4: love hate relationshipi bought one first paperwhites pleased constant companion suppose ive read average book every three day past however many year wouldnt give youd pry cold dead fingersfor sundry logistical reason ive also made good use amazon kindle app iphone paperwhite screen naturally cool usability delivers work well attraction companion kindleof course aspect paperwhite would like critique ah knew coming somewhere didnt youas member bookbub get daily list alert book deal chosen genre take many however ive found even best world cant keep day seems every book read ive bought two there much good stuff accumulative effect number book actually paperwhite creeping ever upward time mind ive noticed pageturning remained exactly every action kindle become positively glacial slow slow think malfunctioning general consensus appears expected one many book downloaded onto kindle begin behave flakey manner drive mad amazon state hold thousand book believe figure would need second paperwhite read im waiting action complete first oneread
Sentence 5: love iti say upfront dont like coroporate hermetically closed stuff like anything apple case amazon like device put anything want use buti fairly happy user nook touch several year couldnt use functionality since live serbia lost nook since device actually fully used serbia buying book using online capability except kindle since one except amazon ship serbia since ive actually happy amazon customer since friend account since since kindle definitely best technology buy itso read many review screenlight paperwhite similar device problem mine light disperses fine except black blotch maybe see picture bottom screen actually shadow black plastic casing thus cant really avoided see picture without light blotch light outthe paperwhites screen marvelous ppi touchscreen work fine store work serbia two day ive using im happy guyi get hang make sideloaded book behave least almost like amazon book thats fine thats one thing id like see amazon future upgrade make kindle treat sideloaded book like one bought directly sharing funcion quote goodreads enabled onthe size perfect sits well hand light doesnt hurt eye dark like light tab packaging fine problem remains seen battery lifeso far recommend

In [5]:
# 2. Build a vacabulary of unique words

vocabulary=sorted(set(
    word 
    for sentence in sentences 
    for word in sentence.split()))

In [6]:
# 3. Create one hot vectors

one_hot_vectors=[]

for sentence in sentences:
    words = set(sentence.split())

    vector=[1 if word in words else 0 for word in vocabulary]

    one_hot_vectors.append(vector)

In [7]:
# Display

one_hot_df=pd.DataFrame(one_hot_vectors, columns = vocabulary)

In [8]:
print(vocabulary)

['account', 'accumulative', 'action', 'actually', 'adjustmentits', 'admit', 'adore', 'ah', 'alert', 'almost', 'also', 'always', 'amazon', 'amazoni', 'anything', 'app', 'appears', 'apple', 'ask', 'aspect', 'attraction', 'auto', 'average', 'avoided', 'awesome', 'back', 'basis', 'battery', 'become', 'begin', 'behave', 'believe', 'best', 'black', 'blotch', 'book', 'bookbub', 'bottom', 'bought', 'brave', 'buti', 'buy', 'buying', 'cant', 'capability', 'case', 'casing', 'casual', 'certain', 'change', 'changing', 'chosen', 'closed', 'cold', 'coming', 'companion', 'complete', 'consensus', 'considering', 'constant', 'cool', 'coroporate', 'could', 'couldnt', 'course', 'creeping', 'critique', 'custom', 'customer', 'daily', 'dark', 'day', 'dead', 'deal', 'deciding', 'definitely', 'delivers', 'delivery', 'desire', 'device', 'didnt', 'directly', 'disperses', 'dive', 'divergent', 'doesnt', 'dollar', 'dont', 'downloaded', 'dragon', 'drive', 'easy', 'effect', 'either', 'enabled', 'ended', 'enjoying', 'entire', 'ereaderi', 'even', 'ever', 'every', 'exactly', 'except', 'expected', 'expense', 'experience', 'experienced', 'extra', 'eye', 'fair', 'fairly', 'far', 'feeling', 'figure', 'fine', 'fingersfor', 'fire', 'first', 'flakey', 'forward', 'found', 'friend', 'full', 'fully', 'funcion', 'functionality', 'future', 'game', 'general', 'genre', 'get', 'girl', 'give', 'glacial', 'glad', 'go', 'good', 'goodreads', 'gotten', 'great', 'guyi', 'half', 'hand', 'hang', 'happy', 'hard', 'harry', 'hate', 'havent', 'hermetically', 'hindered', 'history', 'hold', 'however', 'hunger', 'hurt', 'id', 'im', 'included', 'initially', 'inside', 'inspire', 'inspired', 'international', 'investment', 'iphone', 'isnt', 'iti', 'itso', 'ive', 'jump', 'keep', 'key', 'kindle', 'kindleof', 'knew', 'least', 'left', 'less', 'let', 'level', 'lifeso', 'light', 'like', 'list', 'little', 'live', 'logistical', 'long', 'lost', 'love', 'loving', 'mad', 'made', 'make', 'malfunctioning', 'man', 'manner', 'many', 'marvelous', 'may', 'maybe', 'member', 'mind', 'mine', 'model', 'money', 'moreallow', 'moving', 'much', 'naturally', 'need', 'never', 'new', 'nook', 'noticed', 'number', 'oh', 'one', 'oneread', 'online', 'onthe', 'onto', 'option', 'original', 'others', 'outthe', 'owned', 'packaging', 'page', 'pageturning', 'paperwhite', 'paperwhites', 'party', 'past', 'paying', 'perfect', 'pick', 'picture', 'plastic', 'pleased', 'positively', 'potter', 'ppi', 'preface', 'press', 'pricey', 'problem', 'pry', 'purchasing', 'put', 'quote', 'read', 'reader', 'reading', 'readingalso', 'really', 'reason', 'receive', 'receptive', 'recommend', 'regardless', 'regret', 'regretsi', 'relate', 'relationshipi', 'remained', 'remains', 'review', 'said', 'say', 'screen', 'screenlight', 'second', 'see', 'seems', 'seen', 'sensitive', 'serbia', 'series', 'service', 'setting', 'several', 'shadow', 'shall', 'sharing', 'ship', 'shipping', 'sideloaded', 'similar', 'simple', 'simply', 'since', 'sits', 'size', 'slow', 'somewhere', 'soon', 'specific', 'spending', 'state', 'still', 'stop', 'store', 'stuff', 'sundry', 'suppose', 'tab', 'take', 'tattoo', 'technology', 'thats', 'theirsfast', 'there', 'thing', 'think', 'thinking', 'third', 'thousand', 'three', 'thus', 'time', 'title', 'today', 'ton', 'touch', 'touchscreen', 'tracking', 'treat', 'trilogy', 'trouble', 'turn', 'two', 'upfront', 'upgrade', 'upward', 'usability', 'use', 'used', 'user', 'using', 'voyage', 'voyagefortunately', 'waiting', 'want', 'week', 'well', 'wellmake', 'went', 'without', 'work', 'world', 'worry', 'would', 'wouldnt', 'year', 'yet', 'youas', 'youd', 'youll']

In [9]:
one_hot_df

,account,accumulative,action,actually,adjustmentits,admit,adore,ah,alert,almost,...,work,world,worry,would,wouldnt,year,yet,youas,youd,youll
0,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,0,0,0,0,0,1,1,0,0,0,...,0,1,0,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,1,1,1,0,0,0,1,1,0,...,1,1,0,1,1,1,0,1,1,0
4,1,0,0,1,0,0,0,0,0,1,...,1,0,0,0,0,1,0,0,0,0

### Task 2: One-Hot Encoding using Scikit-learn

In [10]:
# 1. Use countvectorizer(binary=True)

from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv=CountVectorizer(binary=True)

In [12]:
# 2. Fit and transform the selected sentences

encoded_matrix=cv.fit_transform(sentences).toarray()

In [13]:
# 3. Print

print("Vocabulary :",cv.vocabulary_)

print("Encoded matrix :",encoded_matrix)

Vocabulary : {'paperwhite': 232, 'voyage': 342, 'regretsi': 264, 'initially': 160, 'trouble': 331, 'deciding': 74, 'review': 269, 'less': 179, 'said': 270, 'thing': 315, 'great': 140, 'spending': 300, 'money': 207, 'go': 136, 'voyagefortunately': 343, 'friend': 122, 'owned': 228, 'ended': 95, 'buying': 42, 'basis': 26, 'model': 206, 'ppi': 244, 'dollar': 86, 'jump': 171, 'turn': 332, 'pricey': 247, 'page': 230, 'press': 246, 'isnt': 167, 'always': 11, 'sensitive': 278, 'fine': 115, 'specific': 299, 'setting': 282, 'dont': 87, 'need': 212, 'auto': 21, 'light': 183, 'adjustmentits': 4, 'week': 346, 'loving': 192, 'regret': 263, 'touch': 326, 'screen': 272, 'receptive': 260, 'easy': 91, 'use': 338, 'keep': 172, 'regardless': 262, 'time': 322, 'day': 71, 'case': 45, 'hard': 146, 'change': 49, 'either': 93, 'youll': 360, 'changing': 50, 'level': 181, 'certain': 48, 'every': 101, 'readingalso': 256, 'glad': 135, 'went': 349, 'international': 164, 'shipping': 288, 'option': 224, 'amazon': 12, 'extra': 108, 'expense': 105, 'delivery': 77, 'tracking': 328, 'didnt': 80, 'worry': 353, 'custom': 67, 'may': 201, 'used': 339, 'third': 318, 'party': 234, 'service': 281, 'one': 219, 'simply': 292, 'could': 62, 'ask': 18, 'moreallow': 208, 'preface': 245, 'little': 186, 'history': 152, 'casual': 47, 'reader': 254, 'nook': 215, 'simple': 291, 'ive': 170, 'read': 253, 'harry': 147, 'potter': 243, 'series': 280, 'girl': 132, 'dragon': 89, 'tattoo': 310, 'brave': 39, 'new': 214, 'world': 352, 'key': 173, 'title': 323, 'fair': 110, 'say': 271, 'get': 131, 'much': 210, 'many': 199, 'others': 226, 'gotten': 139, 'theirsfast': 313, 'forward': 120, 'today': 324, 'full': 123, 'kindle': 174, 'admit': 5, 'im': 158, 'love': 191, 'reading': 255, 'let': 180, 'relate': 265, 'back': 25, 'investment': 165, 'experience': 106, 'receive': 259, 'buy': 41, 'paying': 236, 'entire': 97, 'included': 159, 'amazoni': 13, 'hunger': 155, 'game': 128, 'trilogy': 330, 'shall': 285, 'moving': 209, 'onto': 223, 'divergent': 84, 'soon': 298, 'hindered': 151, 'past': 235, 'year': 356, 'never': 213, 'inspired': 163, 'pick': 238, 'hand': 143, 'dive': 83, 'feeling': 113, 'oh': 218, 'man': 197, 'awesome': 24, 'however': 154, 'desire': 78, 'adore': 6, 'considering': 58, 'purchasing': 250, 'stop': 303, 'thinking': 317, 'downloaded': 88, 'book': 35, 'ton': 325, 'still': 302, 'half': 142, 'battery': 27, 'left': 178, 'wellmake': 348, 'happy': 145, 'inspire': 162, 'inside': 161, 'want': 345, 'ereaderi': 98, 'enjoying': 96, 'far': 112, 'original': 225, 'fire': 117, 'since': 293, 'make': 195, 'eye': 109, 'hurt': 156, 'long': 189, 'havent': 149, 'experienced': 107, 'yet': 357, 'hate': 148, 'relationshipi': 266, 'bought': 38, 'first': 118, 'paperwhites': 233, 'pleased': 241, 'constant': 59, 'companion': 55, 'suppose': 307, 'average': 22, 'three': 320, 'wouldnt': 355, 'give': 133, 'youd': 359, 'pry': 249, 'cold': 53, 'dead': 72, 'fingersfor': 116, 'sundry': 306, 'logistical': 188, 'reason': 258, 'also': 10, 'made': 194, 'good': 137, 'app': 15, 'iphone': 166, 'naturally': 211, 'cool': 60, 'usability': 337, 'delivers': 76, 'work': 351, 'well': 347, 'attraction': 20, 'kindleof': 175, 'course': 64, 'aspect': 19, 'would': 354, 'like': 184, 'critique': 66, 'ah': 7, 'knew': 176, 'coming': 54, 'somewhere': 297, 'youas': 358, 'member': 203, 'bookbub': 36, 'daily': 69, 'list': 185, 'alert': 8, 'deal': 73, 'chosen': 51, 'genre': 130, 'take': 309, 'found': 121, 'even': 99, 'best': 32, 'cant': 43, 'seems': 276, 'two': 333, 'there': 314, 'stuff': 305, 'accumulative': 1, 'effect': 92, 'number': 217, 'actually': 3, 'creeping': 65, 'ever': 100, 'upward': 336, 'mind': 204, 'noticed': 216, 'pageturning': 231, 'remained': 267, 'exactly': 102, 'action': 2, 'become': 28, 'positively': 242, 'glacial': 134, 'slow': 296, 'think': 316, 'malfunctioning': 196, 'general': 129, 'consensus': 57, 'appears': 16, 'expected': 104, 'begin': 29, 'behave': 30, 'flakey': 119, 'manner': 198, 'drive': 90, 'mad': 193, 'state': 301, 'hold': 153, 'thousand': 319, 'believe': 31, 'figure': 114, 'second': 274, 'waiting': 344, 'complete': 56, 'oneread': 220, 'iti': 168, 'upfront': 334, 'coroporate': 61, 'hermetically': 150, 'closed': 52, 'anything': 14, 'apple': 17, 'device': 79, 'put': 251, 'buti': 40, 'fairly': 111, 'user': 340, 'several': 283, 'couldnt': 63, 'functionality': 126, 'live': 187, 'serbia': 279, 'lost': 190, 'fully': 124, 'using': 341, 'online': 221, 'capability': 44, 'except': 103, 'ship': 287, 'customer': 68, 'account': 0, 'definitely': 75, 'technology': 311, 'itso': 169, 'screenlight': 273, 'similar': 290, 'problem': 248, 'mine': 205, 'disperses': 82, 'black': 33, 'blotch': 34, 'maybe': 202, 'see': 275, 'picture': 239, 'bottom': 37, 'shadow': 284, 'plastic': 240, 'casing': 46, 'thus': 321, 'really': 257, 'avoided': 23, 'without': 350, 'outthe': 227, 'marvelous': 200, 'touchscreen': 327, 'store': 304, 'guyi': 141, 'hang': 144, 'sideloaded': 289, 'least': 177, 'almost': 9, 'thats': 312, 'id': 157, 'future': 127, 'upgrade': 335, 'treat': 329, 'directly': 81, 'sharing': 286, 'funcion': 125, 'quote': 252, 'goodreads': 138, 'enabled': 94, 'onthe': 222, 'size': 295, 'perfect': 237, 'sits': 294, 'doesnt': 85, 'dark': 70, 'tab': 308, 'packaging': 229, 'remains': 268, 'seen': 277, 'lifeso': 182, 'recommend': 261}
Encoded matrix : [[0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 1 1 0]
 [1 0 0 ... 0 0 0]]

## PART 2 - Bag of Words (BoW)

### Task 3: Bag of Words Representation

In [14]:
# Use the CountVectorizer

from sklearn.feature_extraction.text import CountVectorizer

In [15]:
bow=CountVectorizer()

In [16]:
# 2. Fit the entire dataset

texts=data['final_clean_text'].dropna().astype(str)

In [17]:
print("Number of texts: ",len(texts))

Number of texts:  1580

In [18]:
# 3. Transform text into BoW vectors
#  
bow_matrix=bow.fit_transform(texts)
bow_vocabulary=bow.get_feature_names_out()

In [19]:
# Display:

print("Vocabulary Size:",len(bow_vocabulary))
print("Sample feature vectors:",bow_matrix[:5].toarray())

Vocabulary Size: 7481

Sample feature vectors: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

### Task 4: Understanding Word Frequency

In [20]:
# Get Vocabulary

words=bow.get_feature_names_out()

In [21]:
# Calculate total frequency of each word

word_frequency=bow_matrix.sum(axis=0)

In [22]:
# Convert into 1D array

word_frequency=word_frequency.A1

In [23]:
# Create DataFrame

frequency_df=pd.DataFrame({'word':words, 'frequency':word_frequency})

In [24]:
#  Sort by frequency

frequency_df=frequency_df.sort_values(by='frequency',ascending=False)

In [25]:
frequency_df

               word  frequency
2413           fire       1560
3590         kindle       1506
237          amazon       1452
3749           like       1255
5525         review       1189
...             ...        ...
4346        nonstop          1
1250  configuration          1
1249    confidently          1
4350      noordered          1
7480           zumi          1

[7481 rows x 2 columns]

In [26]:
# Top 10 most frequent words

top_10=frequency_df.head(10)

In [27]:
print("Top 10 most frequent words:\n", top_10)

Top 10 most frequent words:
            word  frequency
2413       fire       1560
3590     kindle       1506
237      amazon       1452
3749       like       1255
5525     review       1189
2802      great       1095
7017        use       1014
2964  headphone        942
4474        one        928
1614     device        907

In [28]:
# Least frequent words
least_frequent=frequency_df[frequency_df['frequency']==frequency_df['frequency'].min()]

In [29]:
print("Least frequent words:\n",least_frequent)

Least frequent words:
                word  frequency
7250       welllove          1
5712        seasoni          1
5826       shipread          1
667           blaze          1
662         blaming          1
...             ...        ...
4346        nonstop          1
1250  configuration          1
1249    confidently          1
4350      noordered          1
7480           zumi          1

[3274 rows x 2 columns]

Explain how BoW captures frequency information?
- The Bag of Words (BoW) model captures frequency information by converting text into numerical vectors where each dimension represents a known word, and the value in that dimension represents how many times that word appears. It throws away all grammar , context ,and word order treating the document like a literal bag of disconnected words
1. Vocubulary building
2. Vector initialization
3. Frequency Counting

## PART 3 - N-Grams

### Task 5 : Unigrams, Bigrams & Trigrams

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

In [31]:
# 1. Create BoW using: 

unigram=CountVectorizer(ngram_range=(1,1))
bigram=CountVectorizer(ngram_range=(2,2))
trigram=CountVectorizer(ngram_range=(3,3))

In [32]:
unigram_matrix=unigram.fit_transform(texts)
unigram_vocabulary=unigram.get_feature_names_out()

In [33]:
bigram_matrix=bigram.fit_transform(texts)
bigram_vocabulary=bigram.get_feature_names_out()

In [34]:
trigram_matrix=trigram.fit_transform(texts)
trigram_vocabulary=trigram.get_feature_names_out()

In [35]:
# 2. Compare:

print(f"Vocabulary Size :", len(unigram_vocabulary),len(bigram_vocabulary),len(trigram_vocabulary))

print("Sample feature vectors :\n", unigram_matrix[:5].toarray(),bigram_matrix[:5].toarray(),trigram_matrix[:5].toarray())

Vocabulary Size : 7481 44220 53571
Sample feature vectors :
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

### Task 6 : Combined N-Grams

In [36]:
# Use ngram_range

cv=CountVectorizer(ngram_range=(1,2))

In [37]:
# Observe how context improves compared to unigram alone

cv_matrix=cv.fit_transform(texts)
cv_vocabulary=cv.get_feature_names_out()

In [38]:
cv_matrix.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(1580, 51701))

In [40]:
print("CV for (1,2):",len(cv_vocabulary))
print("Unigram BoW:",len(unigram_vocabulary))

CV for (1,2): 51701
Unigram BoW: 7481