In [156]:
import pandas as pd

# Assignment 17 : Text Cleaning, Preprocessing & NLP Pipeline

## PART 1 - NLP Pipeline & Basic Text Cleaning

### Task 1 : Understanding Raw Text Data

In [157]:
# 1. Load the text dataset using pandas

data=pd.read_csv('amazon_reviews.csv')

In [158]:
data=data[['reviews.title','reviews.text','reviews.sourceURLs']]

In [159]:
data['reviews']=data['reviews.title']+data['reviews.text']

In [160]:
data.drop(columns=['reviews.title','reviews.text'],inplace=True)

In [161]:
# 2. Print

In [162]:
data.head() # first 5 text samples

,reviews.sourceURLs,reviews
0,https://www.amazon.com/Kindle-Paperwhite-High-...,"Paperwhite voyage, no regrets!I initially had ..."
1,https://www.amazon.com/Kindle-Paperwhite-High-...,One Simply Could Not Ask For MoreAllow me to p...
2,https://www.amazon.com/Kindle-Paperwhite-High-...,Great for those that just want an e-readerI am...
3,https://www.amazon.com/Kindle-Paperwhite-High-...,Love / Hate relationshipI bought one of the fi...
4,https://www.amazon.com/Kindle-Paperwhite-High-...,I LOVE ITI have to say upfront - I don't like ...

In [163]:
data['reviews'].str.len()  # Length of each text

0       1094.0
1       1457.0
2        224.0
3       1695.0
4       1925.0
         ...
1592     399.0
1593     766.0
1594     295.0
1595     283.0
1596     594.0
Name: reviews, Length: 1597, dtype: float64

In [164]:
# 3. Identify common issues in raw text

In [165]:
data['reviews'][0]

"Paperwhite voyage, no regrets!I initially had trouble deciding between the paperwhite and the voyage because reviews more or less said the same thing: the paperwhite is great, but if you have spending money, go for the voyage.Fortunately, I had friends who owned each, so I ended up buying the paperwhite on this basis: both models now have 300 ppi, so the 80 dollar jump turns out pricey the voyage's page press isn't always sensitive, and if you are fine with a specific setting, you don't need auto light adjustment).It's been a week and I am loving my paperwhite, no regrets! The touch screen is receptive and easy to use, and I keep the light at a specific setting regardless of the time of day. (In any case, it's not hard to change the setting either, as you'll only be changing the light level at a certain time of day, not every now and then while reading).Also glad that I went for the international shipping option with Amazon. Extra expense, but delivery was on time, with tracking, and I didnt need to worry about customs, which I may have if I used a third party shipping service."

In [166]:
data['reviews'][100]

'Great look for Dot.A great looking cover for the Echo Dot. It gives the Dot a softer and more elegant look. I feel that it is a little pricy for what you get but I do not regret my decision to buy this case.'

In [167]:
# Uppercase / lowercase mismatch 
# numbers also present
# punctuations marks
# Extra spaces also present

### Task 2: Basic Text Cleaning

#### Apply the following basic cleaning steps:

In [168]:
import re

In [169]:
# 1. Convert text to lowercase

data['clean_text_basic']=data['reviews'].str.lower()

In [170]:
# 2. Remove punctuation

def remove_punctuation(text):
    if pd.isna(text):
        return ""
    return re.sub(r"[^\w\s]","",text)

In [171]:
data['clean_text_basic']=data['clean_text_basic'].apply(remove_punctuation)

In [172]:
# 3. Remove numbers

def remove_number(text):
    if pd.isna(text):
        return 0
    return re.sub(r'\d+',"",str(text))

In [173]:
data['clean_text_basic']=data['clean_text_basic'].apply(remove_number)

In [174]:
# 4. remove extra whitespaces

def remove_extra_whitespace(text):
    if pd.isna(text):
        return ""
    return re.sub(r'\s+',' ',str(text)).strip()

In [175]:
data['clean_text_basic']=data['clean_text_basic'].apply(remove_extra_whitespace)

In [176]:
# Compare original text vs cleaned text 

data.head()

,reviews.sourceURLs,reviews,clean_text_basic
0,https://www.amazon.com/Kindle-Paperwhite-High-...,"Paperwhite voyage, no regrets!I initially had ...",paperwhite voyage no regretsi initially had tr...
1,https://www.amazon.com/Kindle-Paperwhite-High-...,One Simply Could Not Ask For MoreAllow me to p...,one simply could not ask for moreallow me to p...
2,https://www.amazon.com/Kindle-Paperwhite-High-...,Great for those that just want an e-readerI am...,great for those that just want an ereaderi am ...
3,https://www.amazon.com/Kindle-Paperwhite-High-...,Love / Hate relationshipI bought one of the fi...,love hate relationshipi bought one of the firs...
4,https://www.amazon.com/Kindle-Paperwhite-High-...,I LOVE ITI have to say upfront - I don't like ...,i love iti have to say upfront i dont like cor...

## PART 2 - Advanced Text Cleaning

In [177]:
data['clean_text_basic']=data['clean_text_basic']+data['reviews.sourceURLs']

In [178]:
data.drop(columns=['reviews.sourceURLs'],inplace=True)

In [179]:
data.head()

,reviews,clean_text_basic
0,"Paperwhite voyage, no regrets!I initially had ...",paperwhite voyage no regretsi initially had tr...
1,One Simply Could Not Ask For MoreAllow me to p...,one simply could not ask for moreallow me to p...
2,Great for those that just want an e-readerI am...,great for those that just want an ereaderi am ...
3,Love / Hate relationshipI bought one of the fi...,love hate relationshipi bought one of the firs...
4,I LOVE ITI have to say upfront - I don't like ...,i love iti have to say upfront i dont like cor...

### Task 3: Removing Noise

In [180]:
# 1. Remove URLs

def remove_url(text):
    if pd.isna(text):
           return ""
    return re.sub(r'https?://\S+|www\.\S+',"",text)

In [181]:
data['clean_text_advanced']=data['clean_text_basic'].apply(remove_url)

In [182]:
data['clean_text_advanced'][0]

'paperwhite voyage no regretsi initially had trouble deciding between the paperwhite and the voyage because reviews more or less said the same thing the paperwhite is great but if you have spending money go for the voyagefortunately i had friends who owned each so i ended up buying the paperwhite on this basis both models now have ppi so the dollar jump turns out pricey the voyages page press isnt always sensitive and if you are fine with a specific setting you dont need auto light adjustmentits been a week and i am loving my paperwhite no regrets the touch screen is receptive and easy to use and i keep the light at a specific setting regardless of the time of day in any case its not hard to change the setting either as youll only be changing the light level at a certain time of day not every now and then while readingalso glad that i went for the international shipping option with amazon extra expense but delivery was on time with tracking and i didnt need to worry about customs which i may have if i used a third party shipping service'

In [183]:
# 2. Remove emails addresses

def remove_email(text):
    email_pattern=r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b'
    return re.sub(email_pattern,'',text)

In [184]:
text="Contact me sunil@gmail.com for more information"

In [185]:
remove_email(text)

'Contact me  for more information'

In [186]:
# 3. Remove HTML tags

def remove_html(text):
    return re.sub(r'<.*?>',"",text)

In [187]:
text="<h1> Hello my name is sunil</h>"

In [188]:
remove_html(text)

' Hello my name is sunil'

In [189]:
# 4. Remove special characters & emojis

def remove_emojis(text):
    emoji_pattern=re.compile(
        "["
        u"\U0001F600-\U0001F64F" # EMOTICONS
        u"\U0001F300-\U0001F5FF" # SYMBOLS AND PICTOGRAPHS 
        u"\U0001F680-\U0001F6FF" # TRANSPORT AND MAP
        u"\U0001F1E0-\U0001F1FF" # FLASH 
        "]+",
        flags=re.UNICODE 
    )
    return emoji_pattern.sub(r'',text)

In [190]:
text="Happy birthday 🎂"

In [191]:
remove_emojis(text)

'Happy birthday '

### Task 4: Handling Stopwords

In [197]:
# 1. Load stopwords using NLTK

from nltk.corpus import stopwords

In [193]:
english=stopwords.words('english')

In [194]:
def without_stopwords(text):
    without_stopword=[]
    for i in text.split():
        if i in english:
            without_stopword.append("")
        else:
            without_stopword.append(i)
        
    return " ".join(without_stopword)

In [ ]:
# 2. Remove stopwords from clean_text_advanced

data['text_no_stopwords']=data['clean_text_advanced'].apply(without_stopwords)

In [196]:
data.head()

,reviews,clean_text_basic,clean_text_advanced,text_no_stopwords
0,"Paperwhite voyage, no regrets!I initially had ...",paperwhite voyage no regretsi initially had tr...,paperwhite voyage no regretsi initially had tr...,paperwhite voyage regretsi initially trouble...
1,One Simply Could Not Ask For MoreAllow me to p...,one simply could not ask for moreallow me to p...,one simply could not ask for moreallow me to p...,one simply could ask moreallow preface ...
2,Great for those that just want an e-readerI am...,great for those that just want an ereaderi am ...,great for those that just want an ereaderi am ...,great want ereaderi enjoying far great...
3,Love / Hate relationshipI bought one of the fi...,love hate relationshipi bought one of the firs...,love hate relationshipi bought one of the firs...,love hate relationshipi bought one first pap...
4,I LOVE ITI have to say upfront - I don't like ...,i love iti have to say upfront i dont like cor...,i love iti have to say upfront i dont like cor...,love iti say upfront dont like coroporate ...

### Task 5: Handling Repeated characters & slang (Optional)

In [198]:
slang_dict={"u":"you","gr8":"great","btw":"by the way","pls":"please"}

In [ ]:
def normalize_slang(text):
    # Normailize repeated characters
    text=re.sub(r'(.)\1{2,}',r'\1',text)
    # Replace slang words
    words= text.split()
    words=[slang_dict.get(word.lower(),word) for word in words]

    return " ".join(words)

In [202]:
text="Sooo good! U are gr8 btw"

In [203]:
normalize_slang(text)

'So good! you are great by the way'