In [1]:
import pandas as pd

# Assignment 17 : Text Cleaning, Preprocessing & NLP Pipeline

## PART 1 - NLP Pipeline & Basic Text Cleaning

### Task 1 : Understanding Raw Text Data

In [2]:
# 1. Load the text dataset using pandas

data=pd.read_csv('amazon_reviews.csv')

In [3]:
data=data[['reviews.title','reviews.text','reviews.sourceURLs']]

In [4]:
data['reviews']=data['reviews.title']+data['reviews.text']

In [5]:
data.drop(columns=['reviews.title','reviews.text'],inplace=True)

In [6]:
# 2. Print

In [7]:
data.head() # first 5 text samples

,reviews.sourceURLs,reviews
0,https://www.amazon.com/Kindle-Paperwhite-High-...,"Paperwhite voyage, no regrets!I initially had ..."
1,https://www.amazon.com/Kindle-Paperwhite-High-...,One Simply Could Not Ask For MoreAllow me to p...
2,https://www.amazon.com/Kindle-Paperwhite-High-...,Great for those that just want an e-readerI am...
3,https://www.amazon.com/Kindle-Paperwhite-High-...,Love / Hate relationshipI bought one of the fi...
4,https://www.amazon.com/Kindle-Paperwhite-High-...,I LOVE ITI have to say upfront - I don't like ...

In [8]:
data['reviews'].str.len()  # Length of each text

0       1094.0
1       1457.0
2        224.0
3       1695.0
4       1925.0
         ...
1592     399.0
1593     766.0
1594     295.0
1595     283.0
1596     594.0
Name: reviews, Length: 1597, dtype: float64

In [9]:
# 3. Identify common issues in raw text

In [10]:
data['reviews'][0]

"Paperwhite voyage, no regrets!I initially had trouble deciding between the paperwhite and the voyage because reviews more or less said the same thing: the paperwhite is great, but if you have spending money, go for the voyage.Fortunately, I had friends who owned each, so I ended up buying the paperwhite on this basis: both models now have 300 ppi, so the 80 dollar jump turns out pricey the voyage's page press isn't always sensitive, and if you are fine with a specific setting, you don't need auto light adjustment).It's been a week and I am loving my paperwhite, no regrets! The touch screen is receptive and easy to use, and I keep the light at a specific setting regardless of the time of day. (In any case, it's not hard to change the setting either, as you'll only be changing the light level at a certain time of day, not every now and then while reading).Also glad that I went for the international shipping option with Amazon. Extra expense, but delivery was on time, with tracking, and I didnt need to worry about customs, which I may have if I used a third party shipping service."

In [11]:
data['reviews'][100]

'Great look for Dot.A great looking cover for the Echo Dot. It gives the Dot a softer and more elegant look. I feel that it is a little pricy for what you get but I do not regret my decision to buy this case.'

In [12]:
# Uppercase / lowercase mismatch 
# numbers also present
# punctuations marks
# Extra spaces also present

### Task 2: Basic Text Cleaning

#### Apply the following basic cleaning steps:

In [13]:
import re

In [14]:
# 1. Convert text to lowercase

data['clean_text_basic']=data['reviews'].str.lower()

In [15]:
# 2. Remove punctuation

def remove_punctuation(text):
    if pd.isna(text):
        return ""
    return re.sub(r"[^\w\s]","",text)

In [16]:
data['clean_text_basic']=data['clean_text_basic'].apply(remove_punctuation)

In [17]:
# 3. Remove numbers

def remove_number(text):
    if pd.isna(text):
        return 0
    return re.sub(r'\d+',"",str(text))

In [18]:
data['clean_text_basic']=data['clean_text_basic'].apply(remove_number)

In [19]:
# 4. remove extra whitespaces

def remove_extra_whitespace(text):
    if pd.isna(text):
        return ""
    return re.sub(r'\s+',' ',str(text)).strip()

In [20]:
data['clean_text_basic']=data['clean_text_basic'].apply(remove_extra_whitespace)

In [21]:
# Compare original text vs cleaned text 

data.head()

,reviews.sourceURLs,reviews,clean_text_basic
0,https://www.amazon.com/Kindle-Paperwhite-High-...,"Paperwhite voyage, no regrets!I initially had ...",paperwhite voyage no regretsi initially had tr...
1,https://www.amazon.com/Kindle-Paperwhite-High-...,One Simply Could Not Ask For MoreAllow me to p...,one simply could not ask for moreallow me to p...
2,https://www.amazon.com/Kindle-Paperwhite-High-...,Great for those that just want an e-readerI am...,great for those that just want an ereaderi am ...
3,https://www.amazon.com/Kindle-Paperwhite-High-...,Love / Hate relationshipI bought one of the fi...,love hate relationshipi bought one of the firs...
4,https://www.amazon.com/Kindle-Paperwhite-High-...,I LOVE ITI have to say upfront - I don't like ...,i love iti have to say upfront i dont like cor...

## PART 2 - Advanced Text Cleaning

In [22]:
data['clean_text_basic']=data['clean_text_basic']+data['reviews.sourceURLs']

In [23]:
data.drop(columns=['reviews.sourceURLs'],inplace=True)

In [24]:
data.head()

,reviews,clean_text_basic
0,"Paperwhite voyage, no regrets!I initially had ...",paperwhite voyage no regretsi initially had tr...
1,One Simply Could Not Ask For MoreAllow me to p...,one simply could not ask for moreallow me to p...
2,Great for those that just want an e-readerI am...,great for those that just want an ereaderi am ...
3,Love / Hate relationshipI bought one of the fi...,love hate relationshipi bought one of the firs...
4,I LOVE ITI have to say upfront - I don't like ...,i love iti have to say upfront i dont like cor...

### Task 3: Removing Noise

In [25]:
# 1. Remove URLs

def remove_url(text):
    if pd.isna(text):
           return ""
    return re.sub(r'https?://\S+|www\.\S+',"",text)

In [26]:
data['clean_text_advanced']=data['clean_text_basic'].apply(remove_url)

In [27]:
data['clean_text_advanced'][0]

'paperwhite voyage no regretsi initially had trouble deciding between the paperwhite and the voyage because reviews more or less said the same thing the paperwhite is great but if you have spending money go for the voyagefortunately i had friends who owned each so i ended up buying the paperwhite on this basis both models now have ppi so the dollar jump turns out pricey the voyages page press isnt always sensitive and if you are fine with a specific setting you dont need auto light adjustmentits been a week and i am loving my paperwhite no regrets the touch screen is receptive and easy to use and i keep the light at a specific setting regardless of the time of day in any case its not hard to change the setting either as youll only be changing the light level at a certain time of day not every now and then while readingalso glad that i went for the international shipping option with amazon extra expense but delivery was on time with tracking and i didnt need to worry about customs which i may have if i used a third party shipping service'

In [28]:
# 2. Remove emails addresses

def remove_email(text):
    email_pattern=r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b'
    return re.sub(email_pattern,'',text)

In [29]:
text="Contact me sunil@gmail.com for more information"

In [30]:
remove_email(text)

'Contact me  for more information'

In [31]:
# 3. Remove HTML tags

def remove_html(text):
    return re.sub(r'<.*?>',"",text)

In [32]:
text="<h1> Hello my name is sunil</h>"

In [33]:
remove_html(text)

' Hello my name is sunil'

In [34]:
# 4. Remove special characters & emojis

def remove_emojis(text):
    emoji_pattern=re.compile(
        "["
        u"\U0001F600-\U0001F64F" # EMOTICONS
        u"\U0001F300-\U0001F5FF" # SYMBOLS AND PICTOGRAPHS 
        u"\U0001F680-\U0001F6FF" # TRANSPORT AND MAP
        u"\U0001F1E0-\U0001F1FF" # FLASH 
        "]+",
        flags=re.UNICODE 
    )
    return emoji_pattern.sub(r'',text)

In [35]:
text="Happy birthday 🎂"

In [36]:
remove_emojis(text)

'Happy birthday '

### Task 4: Handling Stopwords

In [37]:
# 1. Load stopwords using NLTK

from nltk.corpus import stopwords

In [38]:
english=stopwords.words('english')

In [39]:
def without_stopwords(text):
    without_stopword=[]
    for i in text.split():
        if i in english:
            without_stopword.append("")
        else:
            without_stopword.append(i)
        
    return " ".join(without_stopword)

In [40]:
# 2. Remove stopwords from clean_text_advanced

data['text_no_stopwords']=data['clean_text_advanced'].apply(without_stopwords)

In [41]:
data.head()

,reviews,clean_text_basic,clean_text_advanced,text_no_stopwords
0,"Paperwhite voyage, no regrets!I initially had ...",paperwhite voyage no regretsi initially had tr...,paperwhite voyage no regretsi initially had tr...,paperwhite voyage regretsi initially trouble...
1,One Simply Could Not Ask For MoreAllow me to p...,one simply could not ask for moreallow me to p...,one simply could not ask for moreallow me to p...,one simply could ask moreallow preface ...
2,Great for those that just want an e-readerI am...,great for those that just want an ereaderi am ...,great for those that just want an ereaderi am ...,great want ereaderi enjoying far great...
3,Love / Hate relationshipI bought one of the fi...,love hate relationshipi bought one of the firs...,love hate relationshipi bought one of the firs...,love hate relationshipi bought one first pap...
4,I LOVE ITI have to say upfront - I don't like ...,i love iti have to say upfront i dont like cor...,i love iti have to say upfront i dont like cor...,love iti say upfront dont like coroporate ...

### Task 5: Handling Repeated characters & slang (Optional)

In [42]:
slang_dict={"u":"you","gr8":"great","btw":"by the way","pls":"please"}

In [43]:
def normalize_slang(text):
    # Normailize repeated characters
    text=re.sub(r'(.)\1{2,}',r'\1',text)
    # Replace slang words
    words= text.split()
    words=[slang_dict.get(word.lower(),word) for word in words]

    return " ".join(words)

In [44]:
text="Sooo good! U are gr8 btw"

In [45]:
normalize_slang(text)

'So good! you are great by the way'

## PART 3 - Basic Text Preprocessing in NLP

### Task 6: Tokenization

In [46]:
import nltk

In [47]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [54]:
# apply for those sentence of both word and sentence tokenization

sent_1='My name is Sunil Kumar .'
sent_2='I am studying in GEC Jaipur .'
sent_3='I am current studying about A.I .'
sent_4='I lived in 250km away from home .'

In [52]:
# 1. Perform word tokenization

print(word_tokenize(sent_1))
print(word_tokenize(sent_2))
print(word_tokenize(sent_3))
print(word_tokenize(sent_4))

['My', 'name', 'is', 'Sunil', 'Kumar', '.']
['I', 'am', 'studying', 'in', 'GEC', 'Jaipur', '.']
['I', 'am', 'current', 'studying', 'about', 'A.I', '.']
['I', 'lived', 'in', '250km', 'away', 'from', 'home', '.']

In [53]:
# 2. Perform sentence tokenize

print(sent_tokenize(sent_1))
print(sent_tokenize(sent_2))
print(sent_tokenize(sent_3))
print(sent_tokenize(sent_4))

['My name is Sunil Kumar .']
['I am studying in GEC Jaipur .']
['I am current studying about A.I .']
['I lived in 250km away from home .']

### Task 7: Stemming

In [56]:
# 1. Apply Porter Stemmer 

from nltk.stem import PorterStemmer

ps=PorterStemmer()

In [62]:
words=['running','starting','studying','eating','fairly']

In [75]:
stem_words=[]
for i in words:
    stem_words.append(ps.stem(i))

In [83]:
# 2. compare original words vs stemmed words
print("Original words",words)
print("Stemmed words",stem_words)

Original words ['running', 'starting', 'studying', 'eating', 'fairly']
Stemmed words ['run', 'start', 'studi', 'eat', 'fairli']

### Task 8: Lemmatization

In [84]:
# 1. Apply wordnet lemmatizer

from nltk.stem import WordNetLemmatizer

from nltk.corpus import wordnet

In [86]:
lemmatizer=WordNetLemmatizer()

In [87]:
words

['running', 'starting', 'studying', 'eating', 'fairly']

In [91]:
lem_words=[]
for i in words:
    lem_words.append(lemmatizer.lemmatize(i,pos='v'))

In [92]:
lem_words

['run', 'start', 'study', 'eat', 'fairly']

In [93]:
# 2. Compare stemming vs lemmatization 

print("Stemming results",stem_words)
print("Lemmatization results", lem_words)

Stemming results ['run', 'start', 'studi', 'eat', 'fairli']
Lemmatization results ['run', 'start', 'study', 'eat', 'fairly']

### Task 9: Final NLP Pipeline Creation

In [94]:
# Imports

import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [97]:
# Important resources

nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\skmor\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\skmor\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\skmor\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\skmor\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [99]:
# stopwords
stop_words=stopwords.words('english')

In [100]:
# Lemmatization

lemmatizer=WordNetLemmatizer()

In [125]:
def nlp_preprocess(text):
    
    # 1. Lowercase
    text=str(text).lower()

    # 2. Noise Removal
    text=re.sub(r'[^a-zA-Z\s]','',text)

    # 3. tokenization
    tokens=word_tokenize(text)

    # 4. Stopword removal
    tokens=[word for word in tokens if word not in stop_words]

    # 5. Lemmatization
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return ' '.join(tokens)

In [126]:
data['final_clean_text']=data['reviews'].apply(nlp_preprocess)

In [128]:
data.head()

,reviews,clean_text_basic,clean_text_advanced,text_no_stopwords,final_clean_text
0,"Paperwhite voyage, no regrets!I initially had ...",paperwhite voyage no regretsi initially had tr...,paperwhite voyage no regretsi initially had tr...,paperwhite voyage regretsi initially trouble...,paperwhite voyage regretsi initially trouble d...
1,One Simply Could Not Ask For MoreAllow me to p...,one simply could not ask for moreallow me to p...,one simply could not ask for moreallow me to p...,one simply could ask moreallow preface ...,one simply could ask moreallow preface little ...
2,Great for those that just want an e-readerI am...,great for those that just want an ereaderi am ...,great for those that just want an ereaderi am ...,great want ereaderi enjoying far great...,great want ereaderi enjoying far great reading...
3,Love / Hate relationshipI bought one of the fi...,love hate relationshipi bought one of the firs...,love hate relationshipi bought one of the firs...,love hate relationshipi bought one first pap...,love hate relationshipi bought one first paper...
4,I LOVE ITI have to say upfront - I don't like ...,i love iti have to say upfront i dont like cor...,i love iti have to say upfront i dont like cor...,love iti say upfront dont like coroporate ...,love iti say upfront dont like coroporate herm...

### Task 10 : Observations & Insights

1. Difference between basic and advanced cleaning
- Basic Cleaning ---> basic cleaning removes unwanted characters , lowercasing , punctuations , numbers , removes extra spaces , and formatting from text. It is simpler and faster .

- Advanced Cleaning ----> advanced cleaning goes further by processing the liguistic structure of text using techniques such as tokenization , stopwords removal , stemming , and lemmatization . Its produces text that is more suitable for NLP analysis and machine learning models

2. Why lemmatization is preferred over stemming.
- Lemmatization is preferred over stemming because it converts words into meaningful dictionary forms, while stemming may produce incomplete or meaningless words
- Why lemmatization preferred?
- i. Its preoduces meaningful words
- ii. We considers linguistic / Grammatical information
- iii. Its more accurate then stemming
- iv. Its provides clearer and meaningful text for NLP model

3. Importance of preprocessing in NLP models
- NLP preprocessing means cleaning and transforming raw text into a suitable format before giving to a NLP or Machine learning model
- Why Important
- 1. Removes unnecessary data --> removes punctuations , special charcters , extra spaces , etc .
- 2. Reduces noise ---> makes the text cleaner by removing irrelevant information .
- 3. Standardize text ---> prevent the model from treating them a different words
- 4. Reduces vocubulary size ---> stopword removal and lemmatization can reduce the number of unique words
- 5. Improves model performance ---> clean and consistent input can help the model learn meaningful pattern more efficiently
- 6. Converts text into usable form ---> techniques like tokenization convert sentences into individual words / tokens that NLP algorithms can process
- 7. Improves computational efficiency ---> less unnecssary text means fewer features and potentially faster processing