In [35]:
import pandas as pd

# Assignment 17 : Text Cleaning, Preprocessing & NLP Pipeline

## PART 1 - NLP Pipeline & Basic Text Cleaning

### Task 1 : Understanding Raw Text Data

In [36]:
# 1. Load the text dataset using pandas

data=pd.read_csv('amazon_reviews.csv')

In [39]:
data=data[['reviews.title','reviews.text','reviews.sourceURLs']]

In [40]:
data['reviews']=data['reviews.title']+data['reviews.text']+data['reviews.sourceURLs']

In [48]:
data.drop(columns=['reviews.title','reviews.text','reviews.sourceURLs'],inplace=True)

In [50]:
# 2. Print

In [ ]:
data.head() # first 5 text samples

                                             reviews
0  Paperwhite voyage, no regrets!I initially had ...
1  One Simply Could Not Ask For MoreAllow me to p...
2  Great for those that just want an e-readerI am...
3  Love / Hate relationshipI bought one of the fi...
4  I LOVE ITI have to say upfront - I don't like ...

In [ ]:
data['reviews'].str.len()  # Length of each text

0       1267.0
1       1630.0
2        397.0
3       1868.0
4       2098.0
         ...
1592     994.0
1593    2782.0
1594    2162.0
1595     431.0
1596     742.0
Name: reviews, Length: 1597, dtype: float64

In [43]:
# 3. Identify common issues in raw text

In [55]:
data['reviews'][0]

"Paperwhite voyage, no regrets!I initially had trouble deciding between the paperwhite and the voyage because reviews more or less said the same thing: the paperwhite is great, but if you have spending money, go for the voyage.Fortunately, I had friends who owned each, so I ended up buying the paperwhite on this basis: both models now have 300 ppi, so the 80 dollar jump turns out pricey the voyage's page press isn't always sensitive, and if you are fine with a specific setting, you don't need auto light adjustment).It's been a week and I am loving my paperwhite, no regrets! The touch screen is receptive and easy to use, and I keep the light at a specific setting regardless of the time of day. (In any case, it's not hard to change the setting either, as you'll only be changing the light level at a certain time of day, not every now and then while reading).Also glad that I went for the international shipping option with Amazon. Extra expense, but delivery was on time, with tracking, and I didnt need to worry about customs, which I may have if I used a third party shipping service.https://www.amazon.com/Kindle-Paperwhite-High-Resolution-Display-Built/dp/B00QJDU3KY/ref=lp_6669702011_1_7/132-1677641-8459202?s=amazon-devices&ie=UTF8&qid=1498832761&sr=1-7"

In [56]:
data['reviews'][100]

'Great look for Dot.A great looking cover for the Echo Dot. It gives the Dot a softer and more elegant look. I feel that it is a little pricy for what you get but I do not regret my decision to buy this case.https://www.amazon.com/Amazon-Echo-Case-fits-Generation/dp/B01K9KWA3U/ref=sr_1_18/144-2524480-1433355?s=fiona-hardware&ie=UTF8&qid=1500945240&sr=1-18,https://www.amazon.com/Amazon-Echo-Case-fits-Generation/dp/B01K9KWA3U/ref=sr_1_18/132-5615145-9127409?s=fiona-hardware&ie=UTF8&qid=1500945234&sr=1-18,https://www.amazon.com/Amazon-Echo-Case-fits-Generation/dp/B01K9KWA3U/ref=sr_1_18/133-8378918-9138721?s=fiona-hardware&ie=UTF8&qid=1500944909&sr=1-18,https://www.amazon.com/Amazon-Echo-Case-fits-Generation/dp/B01K9KWA3U/ref=sr_1_18/141-0458241-2772141?s=fiona-hardware&ie=UTF8&qid=1500944905&sr=1-18'

In [57]:
# Uppercase / lowercase mismatch 
# numbers also present
# punctuations marks
# Extra spaces also present

### Task 2: Basic Text Cleaning

#### Apply the following basic cleaning steps:

In [44]:
# 2. Remove punctuation

In [45]:
# 3. Remove numbers

In [46]:
# 4. remove extra whitespaces

In [49]:
data.head()

                                             reviews
0  Paperwhite voyage, no regrets!I initially had ...
1  One Simply Could Not Ask For MoreAllow me to p...
2  Great for those that just want an e-readerI am...
3  Love / Hate relationshipI bought one of the fi...
4  I LOVE ITI have to say upfront - I don't like ...