In [128]:
import pandas as pd

# Assignment 17 : Text Cleaning, Preprocessing & NLP Pipeline

## PART 1 - NLP Pipeline & Basic Text Cleaning

### Task 1 : Understanding Raw Text Data

In [129]:
# 1. Load the text dataset using pandas

data=pd.read_csv('amazon_reviews.csv')

In [130]:
data.columns

Index(['id', 'asins', 'brand', 'categories', 'colors', 'dateAdded',
       'dateUpdated', 'dimension', 'ean', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'prices', 'reviews.date',
       'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating',
       'reviews.sourceURLs', 'reviews.text', 'reviews.title',
       'reviews.userCity', 'reviews.userProvince', 'reviews.username', 'sizes',
       'upc', 'weight'],
      dtype='object')

In [131]:
data=data[['id','name','reviews.title','reviews.text']]

In [132]:
data['reviews']=data['reviews.title']+data['reviews.text']

In [133]:
data=data.drop(columns=['reviews.title','reviews.text'])

In [134]:
data.head()

,id,name,reviews
0,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,"Paperwhite voyage, no regrets!I initially had ..."
1,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,One Simply Could Not Ask For MoreAllow me to p...
2,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Great for those that just want an e-readerI am...
3,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Love / Hate relationshipI bought one of the fi...
4,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,I LOVE ITI have to say upfront - I don't like ...

In [135]:
# 2. print:

## First 5 text samples

data['reviews'].head(5)

0    Paperwhite voyage, no regrets!I initially had ...
1    One Simply Could Not Ask For MoreAllow me to p...
2    Great for those that just want an e-readerI am...
3    Love / Hate relationshipI bought one of the fi...
4    I LOVE ITI have to say upfront - I don't like ...
Name: reviews, dtype: object

In [136]:
## Length of each text 

data['reviews'].astype(str).apply(len)

0       1094
1       1457
2        224
3       1695
4       1925
        ...
1592     399
1593     766
1594     295
1595     283
1596     594
Name: reviews, Length: 1597, dtype: int64

In [137]:
# 3. Identify common issues in raw text

In [138]:
## check uppercase / lowercas mismatch / Punctuation / Numbers / Extra spaces

data['reviews'].sample(10)

915     Great deviceI shopped for a long time until I ...
960     Great sound from small speakerGreat sound qual...
971     It awesomeI the awesome I use it at work at lo...
1536    Awesome Headphones! Longevity An Issue 776 peo...
648     Great case with minor design flawsI love every...
903     Great so farStill in the learning process--loo...
107     An enlarged version of the 7 HDX - Same good i...
909     Great product with good bass for the price.Lov...
41                               I love itGreat. Love it.
321     I like it Amazon...But this is IMPORTANT 5,856...
Name: reviews, dtype: object

### Task 2: Basic Text Cleaning

#### Apply the following basic cleaning steps:

In [139]:
# 1. Convert text to lowercase

# Create new column
data['clean_text_basic']=data['reviews'].astype(str)

data['clean_text_basic']=data['clean_text_basic'].apply(lambda x:x.lower())

In [140]:
# 2. Remove punctuation

In [141]:
# 3. Remove numbers

In [142]:
# 4. remove extra whitespaces

In [143]:
data.head()

,id,name,reviews,clean_text_basic
0,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,"Paperwhite voyage, no regrets!I initially had ...","paperwhite voyage, no regrets!i initially had ..."
1,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,One Simply Could Not Ask For MoreAllow me to p...,one simply could not ask for moreallow me to p...
2,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Great for those that just want an e-readerI am...,great for those that just want an e-readeri am...
3,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,Love / Hate relationshipI bought one of the fi...,love / hate relationshipi bought one of the fi...
4,AVpe7AsMilAPnD_xQ78G,Kindle Paperwhite,I LOVE ITI have to say upfront - I don't like ...,i love iti have to say upfront - i don't like ...